require "global.util.util"
require "global.log.logger"
require "global.net.init"
require "global.timer.timer"
require "global.service.init"
require "global.rpc.rpc_mgr"
require "global.db.db_mgr"
require "global.db.db_proxy"
