
#pragma once

enum E_CONN_TYPE
{
	CONN_TYPE_ERROR 		= 0,
	CONN_TYPE_UNTRUST 		= 1,
	CONN_TYPE_TRUST 		= 2,
};

enum E_SERVER_TYPE
{
	SERVER_TYPE_ROUTER 		= 1,
	SERVER_TYPE_GAME 		= 2,
};

enum MSGID_TYPE
{
	CLIENT_TEST = 1,
	CLIENT_TEST_RET = 2,
};

enum EVENT_TYPE
{
	EVENT_TYPE_NEW_CONNECTION 			= 1,
	EVENT_TYPE_CONNNECT_TO_SUCCESS 		= 2,
	EVENT_TYPE_DISCONNECT 				= 3,
	EVENT_TYPE_TIMER 					= 4,
	EVENT_TYPE_MSG 						= 5,
	EVENT_TYPE_STDIN 					= 6,
};
