
#pragma once

enum E_SERVER_TYPE
{
	SERVER_TYPE_NULL 		= 0,
	SERVER_TYPE_ROUTER 		= 1,
	SERVER_TYPE_SCENE 		= 2,
	SERVER_TYPE_DB 			= 3,
	SERVER_TYPE_BRIDGE 		= 4,
	SERVER_TYPE_LOGIN 		= 5,
	SERVER_TYPE_PUBLIC 		= 6,
	SERVER_TYPE_CROSS 		= 7,
	SERVER_TYPE_PAY 		= 8,
	SERVER_TYPE_CHAT 		= 9,
};

enum
{
	MSGLEN_SIZE 	= 4,
	MSGLEN_MSGID 	= 4, 
	MSGLEN_EXT 		= 8, 

	MSGLEN_HEADER = MSGLEN_SIZE + MSGLEN_MSGID + MSGLEN_EXT,
	MSGLEN_CONTENT_POS = MSGLEN_HEADER,
	MSGLEN_MAX 		= 65000,
};
