
#pragma once

enum E_CONN_TYPE
{
	CONN_TYPE_ERROR 		= 0,
	CONN_TYPE_UNTRUST 		= 1,
	CONN_TYPE_TRUST 		= 2,
};

enum E_SERVER_TYPE
{
	SERVER_TYPE_NULL 		= 0,
	SERVER_TYPE_ROUTER 		= 1,
	SERVER_TYPE_SCENE 		= 2,
	SERVER_TYPE_DB 			= 3,
	SERVER_TYPE_BRIDGE 		= 4,
	SERVER_TYPE_LOGIN 		= 5,
	SERVER_TYPE_PUBLIC 		= 6,
	SERVER_TYPE_CROSS 		= 7,
	SERVER_TYPE_PAY 		= 8,
	SERVER_TYPE_CHAT 		= 9,
};

enum MSGID_TYPE
{
	CLIENT_TEST = 1,
	CLIENT_TEST_RET = 2,
};

enum
{
	MSGLEN_HEAD 	= 4,
	MSGLEN_MSGID 	= 4, 
	MSGLEN_EXT 		= 4, 

	MSGLEN_TEXT_POS = MSGLEN_HEAD + MSGLEN_MSGID + MSGLEN_EXT,
	MSGLEN_MAX 		= 65000,
};
