require "core.util.init"
require "core.global.init"
require "core.obj.sheet_obj"
require "core.log.logger"
require "core.net.init"
require "core.timer.timer"
require "core.server.init"
require "core.rpc.rpc_mgr"
require "core.db.db_mgr"
require "core.http.http_mgr"
require "core.ccall.ccall_funcs"
-- require "core.db.db_proxy"
