require "global.sys.log.logger"
require "global.sys.net.init"
require "global.sys.timer.timer"
require "global.sys.service.service_client"
require "global.sys.service.service_server"
require "global.sys.rpc.remote_call_mgr"
